<?php
/**
 * Created by PhpStorm.
 * User: adryanev
 * Date: 29/09/17
 * Time: 16:46
 */

namespace app\controllers;


use yii\web\Controller;

class LoginController extends Controller
{

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}